//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DbConnection.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobPortalEntities : Microsoft.AspNet.Identity.EntityFramework.IdentityDbContext<JobPortal.Model.ApplicationUser>
    {
    
        public JobPortalEntities()
            : base("data source = DESKTOP - GQ6AKJT\\SA; initial catalog = JobPortal; integrated security = True; MultipleActiveResultSets=True;App=EntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
        public static JobPortalEntities Create()
        {
            return new JobPortalEntities();
        }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
